local mainMod = "SUPER"

local env = {
	QT_QPA_PLATFORM = "wayland;xcb",
	QT_QPA_PLATFORMTHEME = "qt5ct",
	MOZ_ENABLE_WAYLAND = "1",
	WAYLAND_DISPLAY = "wayland-1",
	QT_WAYLAND_DISABLE_WINDOWDECORATION = "1",
	GDK_BACKEND = "wayland",
	SDL_VIDEODRIVER = "wayland",
	T_QPA_PLATFORM = "wayland",
	XDG_SESSION_DESKTOP = "Hyprland",
	XDG_CURRENT_DESKTOP = "Hyprland",
	XDG_SESSION_TYPE = "wayland",
	QT_STYLE_OVERRIDE = "gtk2",
	NIXOS_OZONE_WL = "1",
	XCURSOR_SIZE = "24",
	bitdepth = "8",
}

for key, value in pairs(env) do
	hl.env(key, value)
end

-- Core Configuration Block
hl.config({
	autogenerated = false, -- Removes the yellow warning block

	-- Autostart Services & Applications
	exec_once = {
		'hyprctl plugin load "$HYPR_PLUGIN_DIR/lib/libhyprexpo.so"',
		"dbus-update-activation-environment --systemd --all",
		"swww-daemon",
		"sh ~/nixos/modules/home-manager/rice/hyprland/startup.nu",
		"waybar",
		"dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP",
	},

	-- Environment Variables
	-- Hardware Input Configuration
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		follow_mouse = 1,
		accel_profile = "flat",
		sensitivity = 0,
		touchpad = {
			natural_scroll = false,
		},
	},

	-- General Composition & Compositor Layout
	general = {
		gaps_in = 10,
		gaps_out = 10,
		border_size = 2,
		col = {
			active_border = { colors = { "rgba(cba6f7ff)", "rgba(89b4faff)" }, angle = 45 },
			inactive_border = { colors = { "rgba(313244ff)", "rgba(1e1e2eff)" }, angle = 45 },
		},
		layout = "dwindle",
		allow_tearing = false,
	},

	-- UI Styling and Aesthetics
	decoration = {
		rounding = 16,
		blur = {
			enabled = true,
			special = true,
			ignore_opacity = true,
			size = 5,
			passes = 2,
			new_optimizations = true,
			noise = 0.03,
			contrast = 1.1,
			brightness = 0.9,
		},
	},

	-- Tabbed/Grouped Windows settings
	group = {
		col = {
			border_active = { colors = { "rgba(cba6f7ff)", "rgba(89b4faff)" }, angle = 45 },
			border_inactive = { colors = { "rgba(313244ff)", "rgba(1e1e2eff)" }, angle = 45 },
		},
	},

	-- Animation Timings & Bezier curves
	animations = {
		enabled = true,
		bezier = {
			myBezier = { 0.05, 0.9, 0.1, 1.05 },
		},
		animation = {
			{ "windows", 1, 7, "myBezier" },
			{ "windowsOut", 1, 7, "default", "popin 80%" },
			{ "border", 1, 10, "default" },
			{ "borderangle", 1, 8, "default" },
			{ "fade", 1, 7, "default" },
			{ "workspaces", 1, 6, "default" },
		},
	},

	-- Layout Specific Configurations
	dwindle = {
		-- pseudotile = true,
		preserve_split = true,
	},

	-- Extra Miscellaneous Variables
	misc = {
		force_default_wallpaper = 0,
		focus_on_activate = false,
		enable_anr_dialog = false,
	},

	-- Xwayland Emulation Layer Configurations
	xwayland = {
		force_zero_scaling = true,
	},
})

-- Displays Layout Definitions
hl.monitor({
	output = "DP-1",
	mode = "highrr",
	position = "-2560x0",
	scale = "auto",
	bitdepth = 8,
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "highrr",
	position = "auto",
	scale = "auto",
	bitdepth = 10,
	-- transform = 1,
})

hl.monitor({
	output = "", -- Wildcard for any other connected display
	mode = "preferred",
	position = "auto",
	scale = 1,
})

-- Virtual Workspaces Mapping Assignments
hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "2", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "3", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "4", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "5", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "6", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "7", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "8", monitor = "HDMI-A-1" })
hl.workspace_rule({ workspace = "9", monitor = "DP-2" })
hl.workspace_rule({ workspace = "10", monitor = "DP-2" })
hl.workspace_rule({ workspace = "11", monitor = "DP-2" })

-- =========================================================================
-- Core Inputs / Layout Hotkeys Keybindings
-- =========================================================================

-- Application Executables
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + ALT + RETURN", hl.dsp.exec_cmd('kitty -e "tmux"'))
hl.bind(mainMod .. " + SHIFT + RETURN", hl.dsp.exec_cmd('kitty -e "tmux a"'))

-- Window & WM Controls
hl.bind(mainMod .. " + Q", hl.dsp.window.close()) -- (Replaces killactive)
hl.bind(mainMod .. " + ALT + Q", hl.dsp.exit()) -- (Replaces exit)
hl.bind(mainMod .. " + SHIFT + SPACE", hl.dsp.window.float()) -- (Replaces togglefloating)
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen()) -- (Replaces fullscreen)
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo()) -- (Replaces pseudo)
-- hl.bind(mainMod .. " + S", hl.dsp.layout.toggle_split()) -- (Replaces togglesplit)
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("grimshot copy area"))

-- Menu Launchers
hl.bind(
	mainMod .. " + D",
	hl.dsp.exec_cmd('rofi -show drun -show-icons -display-drun "  Apps" -display-run "  Run"')
)
hl.bind(
	mainMod .. " + SHIFT + D",
	hl.dsp.exec_cmd(
		'nvidia-offload rofi -show drun -show-icons -display-drun "  Apps (dGPU)" -display-run "  Run (dGPU)"'
	)
)

-- Structural Motion Focus
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

-- Active Window Repositioning
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "down" }))

for i = 1, 10 do
	local key = i % 10 -- Maps workspace 10 to the "0" key
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = tostring(i) }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = tostring(i) }))
end

-- Manual Workspace 11 Bindings (MINUS key)
hl.bind(mainMod .. " + MINUS", hl.dsp.focus({ workspace = "11" }))
hl.bind(mainMod .. " + SHIFT + MINUS", hl.dsp.window.move({ workspace = "11" }))

-- Global Quick Toggles
hl.bind(mainMod .. " + Tab", hl.dsp.focus({ workspace = "previous" }))

-- =========================================================================
-- Dynamic Mouse Operations (Replaces legacy hl.bindm)
-- =========================================================================
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.move, { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize, { mouse = true })

-- =========================================================================
-- Passive Audio Engine Layer Controls (Replaces legacy hl.bindl)
-- =========================================================================
hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.0"))
hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- -l 1.0"))
hl.bind("xf86audiomute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))

-- Audio playback keys use the locked flag so they trigger when the lockscreen is active
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind(mainMod .. " + Down", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind(mainMod .. " + Up", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind(mainMod .. " + Right", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind(mainMod .. " + Left", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- =========================================================================
-- Application Behavior Assignment Rules
-- =========================================================================
hl.window_rule({ match = { class = "firefox" }, workspace = 2 })
hl.window_rule({ match = { class = "jetbrains-*" }, workspace = 3 })
hl.window_rule({ match = { class = "obsidian" }, workspace = 5 })
hl.window_rule({ match = { class = "(prismlauncher)|(steam)" }, workspace = 7 })
hl.window_rule({ match = { class = "([Mm]inecraft)" }, workspace = 8 })
hl.window_rule({ match = { class = "([dD]iscord|vesktop|legcord)" }, workspace = 9 })
hl.window_rule({ match = { class = "([Ss]potify)|(pavucontrol)" }, workspace = 10 })

-- Engine Core UI Patch Rules
hl.window_rule({ match = { class = "^(UnrealEditor)$", title = "^\\w*$" }, no_initial_focus = true, no_anim = true })
hl.window_rule({ match = { initial_title = "^(UnrealEditor)$" }, render_unfocused = true })
hl.window_rule({ match = { class = "(UnrealEditor)$" }, no_initial_focus = true })

-- Communications Layout Rules
hl.window_rule({ match = { class = "(vesktop|Vesktop|legcord)" }, no_initial_focus = true })

-- Jetbrains Multi-Window / Tooltip Override Patches
hl.window_rule({
	match = { class = "^(.*jetbrains.*)$", title = "^(win.*)$" },
	no_initial_focus = true,
	no_focus = true,
})
hl.window_rule({ match = { class = "^(.*jetbrains.*)$", title = "^\\s$" }, no_initial_focus = true, no_focus = true })

-- Xwayland Shared Pipeline Hooks
hl.window_rule({
	name = "xwayland-video-bridge-fixes", -- Named rule handles grouping cleanly
	match = { class = "xwaylandvideobridge" },
	opacity = 0.0,
	no_anim = true,
	no_initial_focus = true,
	max_size = { 1, 1 },
	no_blur = true,
})
